general.import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
normal = { family = "FiraCode Nerd Font Mono" }
size = 14.0

[window]
startup_mode = "Maximized"
padding = { x = 5, y = 5 }

[cursor]
style = { shape = "Block", blinking = "On" }
unfocused_hollow = true

[mouse]
hide_when_typing = true

[terminal.shell]
program = "/usr/local/bin/fish"
