general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
normal = { family = "FiraCode Nerd Font Mono" }
size = 15.0

[window]
startup_mode = "Maximized"
padding = { x = 5, y = 5 }

[cursor]
style = { shape = "Block", blinking = "On" }
unfocused_hollow = true

[mouse]
hide_when_typing = true

[terminal.shell]
program = "/usr/local/bin/fish"
args = ["-l"]
