[font]
normal = { family = "FiraCode Nerd Font Mono" }
size = 14.0

[window]
startup_mode = "Maximized"
padding = { x = 5, y = 5 }

[cursor]
style = { shape = "Block", blinking = "On" }
unfocused_hollow = true

[mouse]
hide_when_typing = true
